name: testing

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JFrog CLI
        run: |
          wget -qO - https://releases.jfrog.io/artifactory/jfrog-gpg-public/jfrog_public_gpg.key | sudo apt-key add -
          echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo apt install -y jfrog-cli-v2-jf
          jf intro
          
      - name: Configure JFrog CLI
        run: |
            jfrog config add my-jfrog \
            --url=${{ secrets.JFROG_URL }} \
            --user=${{ secrets.JFROG_USER }} \
            --password=${{ secrets.JFROG_PASSWORD }}
            
      - name: Ping
        run: jf rt ping
        
       



